esphome:
  name: "${name}"
  name_add_mac_suffix: true
  friendly_name: "${friendly_name}"
  on_boot:
    - text_sensor.template.publish:
        id: controller_model
        state: "${controller_model}"

# Enable logging
logger:

text_sensor:
  - platform: template
    name: Controller
    id: controller_model
    icon: "mdi:chip"
    entity_category: "diagnostic"
    update_interval: never
