# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name}"
    password: !secret wifi_fallback_ap_password

captive_portal:

sensor:
  - platform: wifi_signal
    name: "Signal WiFi"
    id: wifi_signal_strength
    # update_interval: never 

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "WiFi IP Address"
      icon: "mdi:ip-network"
    ssid:
      name: "WiFi SSID"
      icon: "mdi:wifi-cog"
    bssid:
      name: AP MAC Address
      icon: "mdi:access-point"
    mac_address:
      name: MAC Address
      icon: "mdi:wifi-cog"
    power_save_mode:
      name: Wifi Power Save Mode
      icon: "mdi:wifi-cog"

