esp32:
  board: seeed_xiao_esp32c6
  framework:
    type: esp-idf

substitutions:
  controller_model: "XIAO ESP32C6"

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

i2c:
  sda: GPIO22
  scl: GPIO23
  scan: True

output:
  - platform: gpio
    pin:
      number: GPIO15
      inverted: true
    id: onboard_led

light:
  - platform: binary
    output: onboard_led
    name: "Onboard LED"

# References
# https://wiki.seeedstudio.com/xiao_esp32c6_getting_started/
# https://github.com/DerekSeaman/ESPHome-Seeed-Xiao-ESP32-C6-Config/tree/main
# https://www.xda-developers.com/built-zigbee-motion-sensor-esp32-c6/